module.exports = {
    httpUnsafeOrigin: 'https://cryptpad.subke.cloud',
    httpSafeOrigin: 'https://sandbox.subke.cloud',
    httpAddress: 'denny-cryptpad_web_1',
    filePath: './datastore/',
    archivePath: './data/archive',
    pinPath: './data/pins',
    taskPath: './data/tasks',
    blockPath: './block',
    blobPath: './blob',
    blobStagingPath: './data/blobstage',
    decreePath: './data/decrees',
    logPath: './data/logs',
    maxUploadSize: 20 * 1024 * 1024,
    logToStdout: false,
    logLevel: 'info',
    logFeedback: false,
    verbose: false,
    installMethod: 'docker',
    adminKeys: [],
};
