module.exports = {
    httpUnsafeOrigin: 'http://0.0.0.0:3712',
    httpSafeOrigin: 'http://0.0.0.0:3713',
    httpAddress: '0.0.0.0',
    httpPort: 3712,
    httpSafePort: 3713,
    websocketPort: 3714,
    filePath: './datastore/',
    archivePath: './data/archive',
    pinPath: './data/pins',
    taskPath: './data/tasks',
    blockPath: './block',
    blobPath: './blob',
    blobStagingPath: './data/blobstage',
    decreePath: './data/decrees',
    logPath: './data/logs',
    maxUploadSize: 20 * 1024 * 1024,
    logToStdout: false,
    logLevel: 'info',
    logFeedback: false,
    verbose: false,
    installMethod: 'docker',
    adminKeys: [],
};
